# Generated by Django 4.2.9 on 2024-01-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("EDMSapp", "0002_emp_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emp_address",
            name="Address",
        ),
        migrations.AddField(
            model_name="emp_address",
            name="city",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="emp_address",
            name="emp_model",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="EDMSapp.edmsmodel",
            ),
        ),
        migrations.AddField(
            model_name="emp_address",
            name="pin",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="emp_address",
            name="state",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
